# Generated by Django 5.1.7 on 2026-05-15 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('movement_type', models.CharField(choices=[('entry', 'Entree'), ('exit', 'Sortie'), ('adjustment', 'Ajustement'), ('return', 'Retour'), ('expired', 'Perime'), ('damaged', 'Endommage')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mouvement stock',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity_received', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=200)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot',
                'ordering': ['expiry_date'],
            },
        ),
    ]
