# Generated by Django 5.1.7 on 2026-05-15 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('sync_type', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull')], max_length=10)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('conflict_resolved_by', models.CharField(blank=True, max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log synchronisation',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('field_name', models.CharField(max_length=100)),
                ('server_value', models.TextField()),
                ('client_value', models.TextField()),
                ('resolved_value', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.synclog')),
            ],
            options={
                'verbose_name': 'Conflit sync',
            },
        ),
    ]
