# Generated by Django 5.1.7 on 2026-05-15 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('prescription_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signed', 'Signee'), ('partially_dispensed', 'Partiellement dispensee'), ('dispensed', 'Dispensee'), ('cancelled', 'Annulee')], default='draft', max_length=25)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescriber', models.ForeignKey(limit_choices_to={'role__name': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sync_version', models.BigIntegerField(default=0)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intraveineux'), ('im', 'Intramusculaire'), ('topical', 'Topique'), ('sublingual', 'Sublingual'), ('rectal', 'Rectal'), ('inhalation', 'Inhalation')], default='oral', max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('is_substitutable', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Ligne ordonnance',
            },
        ),
    ]
