# Generated by Django 5.1.7 on 2026-05-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensation',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='medication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication'),
        ),
    ]
